# Project information
site_name: iCub Tech Docs
site_description: Documentation resources for the iCub & R1 robots
site_author: iCub Tech
copyright: BSD 3-Clause License

repo_name: icub-tech-iit/documentation
repo_url: https://github.com/icub-tech-iit/documentation

theme:
  name: material
  palette:
    accent: amber
  features:
    - tabs
  icon:
    logo: material/robot

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink:
      user: icub-tech-iit
      repo: documentation
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - markdown.extensions.toc:
      permalink: true

nav:
  - iCub Tech Docs:
    - Home Page: index.md

    - iCub Starter Kits:
      - First steps with the Humanoid iCub: icub_starter_kits/first_steps.md

    - iCub HW:
      - Summary: icub_hw.md
      - The iCub Versions Table:
        - Versions Table: icub_versions/index.md
      - The iCub Wiring:
        - Summary: icub_wiring/index.md
        - iCub 1.x: icub_wiring/icub1_x.md
        - iCub 2.x: icub_wiring/icub2_x.md
        - iCub 3.x: icub_wiring/icub3_x.md
      - The iCub Tendons manual:
        - Summary: icub_tendons/index.md
        - Neck: icub_tendons/neck.md
        - Shoulder and Elbow: icub_tendons/shoulder_elbow.md
        - Lower Arm:
          - Definition: icub_tendons/lower_arm.md
          - Version 1:
            - Building Phase:
              - How-to Cable and Needed Parts V1: icub_tendons/hand_cabling_V1.md
            - Repair Phase:
              - Disconnection V1: icub_tendons/remove.md
              - Lower Arm V1: icub_tendons/lower_arm_V1.md
              - Wrist and Hand Cabling V1: icub_tendons/wrist_hand_cabling_V1.md
          - Version 2:
            - Building Phase:
              - How-to Cable and Needed Parts V2: icub_tendons/hand_cabling_V2.md
            - Repair Phase:
              - Disconnection V2: icub_tendons/remove.md
              - Lower Arm V2: icub_tendons/lower_arm_V2.md
              - Wrist and Hand Cabling V2: icub_tendons/wrist_hand_cabling_V2.md
        - Waist, Leg and Ankle: icub_tendons/waist_legs.md
      - The iCub Upgrade Kits:
        - Summary: upgrade_kits/index.md
        - KIT_002 Update of torso capacitors: upgrade_kits/torso_capacitors/support.md
        - KIT_003 Hands Support: upgrade_kits/hands/support.md
        - KIT_004 Update upper arm covers : upgrade_kits/upperarm_cover_icub2_5/support.md
        - KIT_005 Eyes Motor Replacement Support: upgrade_kits/eyes/support.md
        - KIT_006 Update of differential neck pulley: upgrade_kits/differential_neck_pulley/support.md
        - KIT_007 Ankle for climbing stairs : upgrade_kits/ankle_for_stairs/support.md
      - F/T Sensors:
        - Summary: ft_sensors/index.md
        - F/T Sensors: ft_sensors/ft_sensors.md
        - F/T Onboard IMU: ft_sensors/ft_onboard_imu.md
        - Study on change of frame for accelerometer measurements: ft_sensors/change_of_frame_accelerometer.md
      - iCub Kinematics:
        - Summary: icub_kinematics/index.md
        - iCub Joints: icub_kinematics/icub-joints/icub-joints.md
        - iCub Joints Limits: icub_kinematics/icub-joints-limits/icub-joints-limits.md
        - Robot Configuration: icub_kinematics/icub-robot-configuration/icub-robot-configuration.md
        - ICub Model naming conventions: icub_kinematics/icub-model-naming-conventions/icub-model-naming-conventions.md
        - Vergence, Version and Disparity: icub_kinematics/icub-vergence-version/icub-vergence-version.md
        - iCub FW Kinematics: icub_kinematics/icub-forward-kinematics/icub-forward-kinematics.md
        - iCub FW Kinematics Arms:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-arms.md
        - iCub FW Kinematics Fingers:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-fingers.md
        - iCub FW Kinematics Head:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-head.md
        - iCub FW Kinematics Legs:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-legs.md
        - iCub FW Kinematics Inertial:  icub_kinematics/icub-forward-kinematics/icub-forward-kinematics-inertial.md
      - iCub 3:
        - iCub 3 joints specs: icub3/icub3-joints.md
      - Custom components: custom_components/custom_components.md


    - iCub SW:
      - Summary: icub_sw.md
      - Software Installation:
        - Summary: sw_installation/index.md
        - Installation from sources:
          - Superbuild Installation:
            - Windows: sw_installation/windows_from_sources_superbuild.md
            - Linux (Debian/Ubuntu): sw_installation/linux_from_sources_superbuild.md
            - macOS: sw_installation/macos_from_sources_superbuild.md
          - Manual Installation:
            - Linux (Debian/Ubuntu): sw_installation/linux_from_sources_manual.md
        - Installation from pre-compiled binaries:
          - Windows: sw_installation/windows_binaries.md
          - Linux (Debian/Ubuntu): sw_installation/linux_binaries.md
        - Check your installation: sw_installation/check_your_installation.md
        - Installation on specific systems on iCub setup:
          - Superbuild Installation:
            - icub-head: sw_installation/icub_head_superbuild.md
          - Manual Installation:
            - icub-head: sw_installation/icub_head_manual.md
      - Software Versioning Table: sw_versioning_table/index.md
      - The OS for the iCub environment:
        - Summary: icub_operating_systems/index.md
        - The OS on icub-head:
          - Introduction: icub_operating_systems/icubos/icubos.md
          - BIOS Tweaks: icub_operating_systems/icubos/bios.md
          - Installation:
            - Installation from pre-built image: icub_operating_systems/icubos/installation-from-image.md
            - Installation from scratch: icub_operating_systems/icubos/installation-from-scratch.md
          - Networking: icub_operating_systems/icubos/networking.md
          - Bluetooth: icub_operating_systems/icubos/bluetooth.md
          - User environment: icub_operating_systems/icubos/user-env.md
          - Further tasks: icub_operating_systems/icubos/further-tasks.md
        - The OS on PC104 (live USB):
          - Introduction: icub_operating_systems/pc104/icub-live.md
          - Installation: icub_operating_systems/pc104/the-icub-live-installation.md
          - Details: icub_operating_systems/pc104/the-icub-live-details.md
        - The OS on other machines (not on robot):
          - Generic iCub enviroment machines (eg. laptop): icub_operating_systems/other-machines/generic-machine.md
          - The iCub server:
            - The "real" iCub server:
              - Installation from pre-built image: icub_operating_systems/other-machines/icub-server-from-image.md
              - Installation from scratch: icub_operating_systems/other-machines/icub-server-from-scratch.md
            - The laptop used as icub server: icub_operating_systems/other-machines/icub-server-laptop.md
          - The CUDA workstation: icub_operating_systems/other-machines/cuda-workstation.md
      - iCub Setup Multiple Robots:
        - Summary: icub_setup_multiple_robots/index.md
        - How to use two iCub robots in gazebo simulation: icub_setup_multiple_robots/two_robots_simulation.md
        - How to use two real iCub robots on the same network: icub_setup_multiple_robots/two_robots_real.md
      - iCub Firmware:
        - Summary: icub_firmware/index.md
        - Firmware Toolchain Documentation:
          - Summary: icub_firmware/fw_toolchain/index.md
          - Installing Keil: icub_firmware/fw_toolchain/installing_keil.md
          - Installing MPLAB: icub_firmware/fw_toolchain/installing_mplab.md
        - Firmware Documentation: icub_firmware/firmware/firmware.md
        - Associated Firmware: icub_firmware/associated-firmware/associated-firmware.md
        - CanLoader: icub_firmware/canLoader/canLoader.md
      - iCub Microphones:
        - How to use microphones: icub_microphones/icub_microphones.md
      - Robot Calibration:
        - iCub 2.X Robot Calibration: icub_robot_calibration/icub-robot-calibration.md
        - Stereo Calibration: icub_robot_calibration/icub-stereo-calib.md
        - iCub3 Stator-Rotor auto-calibration: icub_robot_calibration/icub3-stator-rotor-autocalibration.md
      - Calibration Types:
        - iCub 2.X and R1 Calibration types: icub_r1_icub3_calibration_types/icub_r1_calibration_types.md
        - iCub3 Calibration types: icub_r1_icub3_calibration_types/icub3_calibration_types.md
      - Configure IP on a setup for ETH boards:
        - Configure IP on a setup for ETH boards: configure_static_ip/configure-static-ip.md
