site_name: 'iCub Tendons Repair Manual'
site_description: 'tbd'
site_author: 'We, the People of the iCub Tech'

# Configuration
#docs_dir: 'data'
theme:
    name: 'material'
    palette:
    #    primary: blue grey
        primary: orange
        accent: amber
    feature:
        tabs: true
    # favicon:
    #     icon: dashboard
    logo:
        icon: dashboard

# Copyright
copyright: 'Copyright &copy; 2019 Istituto Italiano di Tecnologia - iCub Tech'

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.magiclink:
        user: robotology
        repo: assistive-rehab
        repo_url_shortener: true
        repo_url_shorthand: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - markdown.extensions.toc:
        permalink: true

# Page tree
nav:
    - Home: 'index.md'
    - Body parts:
        - Overall: 'introduction.md'
        - Neck: 'Neck.md'
        - Shoulder & Elbow: 'shoulder_elbow.md'
        - Waist & Hip: 'waist_hip.md'
        - types of lower arms: 'Lower_Arm.md'
        - Lower Arm Version 1: 'LowerArmV1.md'
    - License: 'license.md'